#!/usr/bin/env bash

https://blog.smittytone.net/2022/05/07/how-to-do-dns-over-https-on-macos/

mkdir /usr/local/etc/cloudflared

echo "proxy-dns: true
proxy-dns-upstream:
  - https://1.1.1.1/dns-query
  - https://8.8.8.8/dns-query" > /usr/local/etc/cloudflared/config.yaml
